name: Build
on: push

jobs:
  linter:
    name: linter
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: ["3.6", "3.7"]
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Required Python Modules
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Commit Lint
        run: |
          gitlint
